---
name: Regression tests

"on":
  push:
  pull_request:
  workflow_dispatch:

permissions: {}

jobs:
  regression-tests:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - name: "Setup python"
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
      - name: "Prepare test dependencies"
        run: |
          ./scripts/prepare-tests.sh
      - name: "Run tests"
        run: |
          ./scripts/run-tests.sh --cov-fail-under=100
      - name: "Run linting"
        run: |
          ./scripts/lint.sh
